export enum BitacoraAccion {
    Login = 1,
    Logout = 2,
    CrearPersonal = 3,
    ListarPersonal = 4,
    ActualizarPersonal = 5,
    CrearCliente = 6,
    ListarClientes = 7,
    ActualizarCliente = 8,
    CrearMascota = 9,
    ListarMascotas = 10,
    ActualizarMascota = 11,
    CrearReservacion = 12,
    ListarReservacion = 13,
    ActualizarReservacion = 14,
    CrearVacuna = 15,
    ListarVacunas = 16,
    CrearRegVac = 17,
    ListarRegVac = 18,
    ActualizarRegVac = 19,
    ActualizarUsuario = 20
}
